version: '3'
name: stsiguet

services:
  outpainting:
    build: .
#    ports:
#      - "8000:8000"
    container_name: stsiguet-outpainting
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
